#!/bin/bash

currentWorkingRealPath="$1"
thorsAbsPath="$2"

count=$(echo ${currentWorkingRealPath#"${thorsAbsPath}"}/ | awk -F/ '{print NF-2}')
awk -v n="$count" 'BEGIN{while (n-- > 0) printf "../"}'

