#!/bin/bash

# Usage
# classDesc <file> <class>
#
# Gets the class description
#   Name of a parent class (if any)


program=$(cat - <<'AWK_PROGRAM'
BEGIN       {FOUND=0;description="";}
/template/  {next}
/^\/\/ /    {
                if (FOUND == 1)
                {
                    if (description == "") {
                        description=" |\n";
                    }
                    description = sprintf("%s        %s\n",description,substr($0,4));
                    next;
                }
            }
/^\/\//     {
                if (FOUND == 1)
                {
                    if (description == "") {
                        description=" |\n";
                    }
                    description = sprintf("%s        \n",description);
                    next;
                }
            }
/struct/    {
                sub("signed ", "signed-", $0);
                sub("long long", "long-long", $0);
                sub(/\(.*/, "", $0);
                gsub(/[ \t]+/, " ", $0);
                sub(":", "", $0);
                sub("<", "-L", $0);
                sub(">", "-R", $0);
                if (FOUND == 1 && $2 == Name)
                {
                    printf("%s", description);
                    exit;
                }
                description="";
                FOUND=0;
            }
/class/     {
                sub("signed ", "signed-", $0);
                sub("long long", "long-long", $0);
                sub(/\(.*/, "", $0);
                gsub(/[ \t]+/, " ", $0);
                sub(":", "", $0);
                sub("<", "-L", $0);
                sub(">", "-R", $0);
                if (FOUND == 1 && $2 == Name)
                {
                    printf("%s", description);
                    exit;
                }
                description="";
                FOUND=0;
            }
/@class/    {FOUND=1;}
AWK_PROGRAM
)

awk -v Name=$2 "${program}" $1
