#!/bin/bash

# Usage
# classList <file> [<marker>]
#
# Get a list of class in <file> that have a prefix @class<marker>

file=$1
marker=$2

program=$(cat - <<'AWK_PROGRAM'
BEGIN       {FOUND=0;}
/^\/\/ /    {if (FOUND == 1){next;}}
/struct/    {
                if (FOUND == 1)
                {
                    sub(":", "", $2);
                    sub("<", "_", $2);
                    sub(">", "", $2);
                    printf("%s ", $2);
                    FOUND=0;
                }
            }
/class/     {
                if (FOUND == 1)
                {
                    sub(":", "", $2);
                    sub("<", "_", $2);
                    sub(">", "", $2);
                    printf("%s ", $2);
                    FOUND=0;
                }
            }
AWK_PROGRAM
)
program="${program}/@class${marker}[ \t]*$/    {FOUND=1;}"

awk "${program}" ${file}
