#!/bin/bash

# Usage
# classList <file> [<marker>]
#
# Get a list of class in <file> that have a prefix @class<marker>

file=$1
marker=$2

program=$(cat - <<'AWK_PROGRAM'
BEGIN       {FOUND=0;}
/^\/\/ /    {if (FOUND == 1){next;}}
/^\/\//     {if (FOUND == 1){next;}}
/struct/    {
                if (FOUND == 1)
                {
                    $1="";
                    sub("signed ", "signed-", $0);
                    sub("long long", "long-long", $0);
                    sub(/\(.*/, "", $0);
                    gsub(/[ \t]+/, "", $0);
                    gsub(/:.*/, "", $0);
                    sub("<", "-L", $0);
                    sub(">", "-R", $0);
                    printf("%s ", $0);
                    FOUND=0;
                }
            }
/class/     {
                if (FOUND == 1)
                {
                    $1="";
                    sub("signed ", "signed-", $0);
                    sub("long long", "long-long", $0);
                    sub(/\(.*/, "", $0);
                    gsub(/[ \t]+/, "", $0);
                    gsub(/:.*/, "", $0);
                    sub("<", "-L", $0);
                    sub(">", "-R", $0);
                    printf("%s ", $0);
                    FOUND=0;
                }
            }
AWK_PROGRAM
)
program="${program}/@class${marker}[ \t]*$/    {FOUND=1;}"

awk "${program}" ${file}
