#!/bin/bash

# Usage
# classInfo <file> <class>
#
# Gets the class info from a file:
#   Name of a parent class (if any)


program=$(cat - <<'AWK_PROGRAM'
BEGIN       {FOUND=0;}
/template/  {next}
/^\/\/ /    {if (FOUND == 1){next;}}
/struct/    {
                type=$3;
                parent=$4;
                $1="";
                sub("signed ", "signed-", $0);
                sub("long long", "long-long", $0);
                sub(/\(.*/, "", $0);
                gsub(/ \t/, "", $0);
                sub(":", "", $0);
                sub("<", "-L", $0);
                sub(">", "-R", $0);
                if (FOUND == 1 && $2 == Name && type == "public")
                {
                    printf("%s ", parent);
                }
                FOUND=0;
            }
/class/     {
                type=$3;
                parent=$4;
                $1="";
                sub("signed ", "signed-", $0);
                sub("long long", "long-long", $0);
                sub(/\(.*/, "", $0);
                gsub(/ \t/, "", $0);
                sub(":", "", $0);
                sub("<", "-L", $0);
                sub(">", "-R", $0);
                if (FOUND == 1 && $2 == Name && type == "public")
                {
                    printf("%s ", parent);
                }
                FOUND=0;
            }
/@class/    {FOUND=1;}
AWK_PROGRAM
)

awk -v Name=$2 "${program}" $1
