#!/bin/bash

# Usage
# functionList <file> [<marker>]
#
# Get a list of functions in <file> that have a prefix @function<marker>

file=$1
marker=$2

program=$(cat - <<'AWK_PROGRAM'
BEGIN       {FOUND=0;}
/^\/\/ /    {if (FOUND == 1){next;}}
/template/  {next;}
            {
                if (FOUND == 1)
                {
                    split($0, data, "\(");
                    st=match($0, " [^ ]*\\(");
                    sub("<", "_", st);
                    sub(">", "", st);
                    printf("%s ", substr(data[1], st));
                    FOUND=0;
                }
            }
AWK_PROGRAM
)
program="${program}/@function${marker}[ \t]*$/ {FOUND=1}"

awk "${program}" ${file}
