#!/bin/bash

# Usage
# functionDesc <file> <function> <index>
#
# Gets the class description
#   Every comment between @method and the method description.
#       @param and @return values are included.
#


program=$(cat - <<'AWK_PROGRAM'
BEGIN       {FOUND=0;description="";Count=0;}
/\/\/ @param /{
                if (FOUND == 1)
                {
                    st = match($0, "// ");
                    description = sprintf("%s-- %s\n", description, substr($0, st + 10));
                    next
                }
            }
/\/\/ @return /{
                if (FOUND == 1)
                {
                    st = match($0, "// ");
                    description = sprintf("%s-- %s\n", description, substr($0, st + 4));
                    next
                }
            }
/\/\/ /     {
                if (FOUND == 1)
                {
                    if (description == "") {
                        description=" |\n";
                    }
                    st = match($0, "// ");
                    description = sprintf("%s        %s\n",description,substr($0, st + 3));
                    next;
                }
            }
/\/\//      {
                if (FOUND == 1)
                {
                    if (description == "") {
                        description=" |\n";
                    }
                    description = sprintf("%s        \n",description);
                    next;
                }
            }
/^inline$/   {next}
/std::enable/{next}
/template/  {next}
            {
                if (FOUND == 1 )
                {
                    Count++;
                    sub("<", "_", $0);
                    sub(">", "", $0);
                    matchTypeNameString=sprintf("[^ ]* %s\\(", Name);
                    st=match($0, matchTypeNameString);
                    if (st != 0 && Count == Index) {
                        printf("%s", description);
                        exit;
                    }
                }
                FOUND=0;
                description = "";
            }
/@function/ {FOUND=1;}
AWK_PROGRAM
)

awk -v Name=$2 -v Index=$3 "${program}" $1
