#!/bin/bash

# Usage
# packageSectionList
#
# Get a list of class in <file> that have a prefix @class<marker>

program=$(cat - <<'AWK_PROGRAM'
/@class/            {printf("%s\n", substr($2, 8))}
/@function/         {printf("%s\n", substr($2, 11))}
AWK_PROGRAM
)

files=$( find . -type f -name "*.h" | xargs )
cat /dev/null ${files} | awk "${program}" - | sort | uniq | xargs
