#!/bin/bash

set -e

function get_awkScriptToConvertSourceToHeader {
    includeToIgnore=$1
    namespace=$2
    awkScriptToConvertSourceToHeader=$(
cat << AWK_SCRIPT_CONVERT_SRC
BEGIN                           {PRINT=1;DEPTH=0;NS=0;}
/^#include "${includeToIgnore}"/{next;}
/^using namespace ${namespace}(.*);/{if (NS==0){sub(";","", \$3);printf("namespace %s\n{\n", \$3);NS=1;next;}}
/^using namespace/              {print;next}
/^using [^=]*;$/                {if (NS==1){printf("using ::%s\n", \$2);}else{print};next;}
/^#ifdef COVERAGE_TEST/         {if (PRINT==1){SAVEDEPTH=DEPTH;PRINT=0;}}
/^#if/                          {DEPTH+=1;}
/^#endif/                       {DEPTH-=1;if (PRINT == 0 && SAVEDEPTH==DEPTH){PRINT=1;}}
                                {if (PRINT) {print;}}
END                             {if(NS==1){print "}\n";}}
AWK_SCRIPT_CONVERT_SRC
)
    echo "${awkScriptToConvertSourceToHeader}"
}

function get_awkScriptToConvertMakeFileToHeader {
    package=$1
    awkScriptToConvertMakeFileToHeader=$(
cat << AWK_SCRIPT_CONVERT_MAKE
/TARGET/                        {print "TARGET = ${package}.head";next;}
                                {print;}
AWK_SCRIPT_CONVERT_MAKE
)
    echo "${awkScriptToConvertMakeFileToHeader}"
}

awkScriptToConvertConfigFileToHeader=$(
cat << AWK_SCRIPT_CONVERT_CONFIG
/_HEADER_ONLY_INCLUDE/  {\$3="inline";print;next;}
/_HEADER_ONLY/          {\$3="1";print;next;}
                                {print;}
AWK_SCRIPT_CONVERT_CONFIG
)

function convertPackageToHeaderOnly {

    cwd=$(pwd)

    prefix=$1
    package=$2
    directory=$(basename ${cwd})
    namespace=$3
    packageDst=${prefix}/${package}

    echo "Converting Module: ${directory} => ${prefix}/${package}"

    rm -rf ${prefix}/${package}
    mkdir ${prefix}/${package}

    echo "        Copying standard header files"
    cp *.h   ${packageDst} 2> /dev/null || :
    cp *.hpp ${packageDst} 2> /dev/null || :
    cp *.tpp ${packageDst} 2> /dev/null || :

    echo "        Converting Makefile"
    awk "$(get_awkScriptToConvertMakeFileToHeader ${package})" Makefile > ${packageDst}/Makefile

    echo "        Converting Config"
    awk "${awkScriptToConvertConfigFileToHeader}" ${directory}Config.h > ${packageDst}/${directory}Config.h

    echo "        Vera Exclusions"
    if [[ -e vera_exclusions ]]; then
        cp vera_exclusions ${packageDst}/vera_exclusions
    fi

    if [[ -e test ]]; then
        echo "        Copying test files and data"
        cp -R test ${prefix}/${package}
        rm -rf ${prefix}/${package}/test/coverage
        rm -rf ${prefix}/${package}/test/report
        rm -rf ${prefix}/${package}/test/makedependency
    fi

    for loop in $(ls *.cpp 2> /dev/null); do
        file=${loop##*/}
        base=${file%%.cpp}
        echo "        Converting ${loop}  Into: ${packageDst}/${base}.source"
        script=$(get_awkScriptToConvertSourceToHeader ${base}.h ${namespace})
        awk "${script}" ${loop} >  ${packageDst}/${base}.source
    done
    echo
}

proxy=$1
package=$2
namespace=$3
convertPackageToHeaderOnly  "${proxy}" "${package}" "${namespace}"

