#!/bin/bash

echo "Installing G++"
sudo apt-get install -qq g++-9 -y           > /dev/null

echo "Installing Dependencies"
sudo apt-get install python-dev -y          > /dev/null
sudo apt-get install -qq libboost-all-dev   > /dev/null

echo "Setting up G++"
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-9 > /dev/null

echo "Building Boost Co-Routines"
wget -O boost_1_71_0.tar.bz2 https://boostorg.jfrog.io/artifactory/main/release/1.71.0/source/boost_1_71_0.tar.bz2     > /dev/null

bzip2 -d boost_1_71_0.tar.bz2           > /dev/null
tar xf boost_1_71_0.tar                 > /dev/null
cd boost_1_71_0/                        > /dev/null
mkdir -p /tmp/extra                     > /dev/null
./bootstrap.sh --prefix=/tmp/extra      > /dev/null
./b2 cxxflags="-Wno-strict-aliasing -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -Wno-placement-new" --with-system --with-context --with-coroutine  > /dev/null

echo "Building Boost Co-Routines"
sudo ./b2 --with-system --with-context --with-coroutine install > /dev/null
