#!/bin/bash
set -e

CXX=$1
build=${2:-make}
cmakeType=${3}

#
# Change this as required to point at the root of ThorsAnvil code
ROOT=$(pwd)
THORSANVIL_ROOT=$(dirname ${ROOT})

echo mkdir -p bin include lib 3rd/bin 3rd/include 3rd/lib share/man
mkdir -p ../bin ../include ../lib ../3rd/bin ../3rd/include ../3rd/lib ../share/man

if [[ -e ${THORSANVIL_ROOT}/lib/libgtest.a ]]; then
    exit 0
fi

if [[ ! -e ../autotools/m4/boost_base.m4 ]]; then
    wget -O ../autotools/m4/boost_base.m4    'http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_boost_base.m4'
    wget -O ../autotools/m4/boost_sys.m4     'http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_boost_system.m4'
    wget -O ../autotools/m4/boost_python.m4  'http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_boost_python.m4'
    wget -O ../autotools/m4/boost_corout.m4  'http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_boost_coroutine.m4'
    wget -O boost_context.m4                 'http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_boost_context.m4'
    wget -O ../autotools/m4/python_devel.m4  'http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_python_devel.m4'
    wget -O boost_thread.m4                  'http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_boost_thread.m4'

    # Current version does not work with boost
    sed -e 's/boost::.*::fcontext_t\*/auto/' -e 's/boost::.*::make_fcontext/make_fcontext/' -e 's/all.hpp>]]/all.hpp>]namespace boost{namespace context{namespace detail{}}}using namespace boost::context;using namespace boost::context::detail;]/' boost_context.m4 > ../autotools/m4/boost_context.m4
    sed -e 's/-pthreads//' -e 's/-pthread//' -e 's/-lpthread//' boost_thread.m4 > ../autotools/m4/boost_thread.m4
    rm boost_context.m4
    rm boost_thread.m4
fi

GTEST_DIR_PATH=${ROOT}/../googletest/
GTEST_DIR=$(cd "${GTEST_DIR_PATH}";pwd)

if [[ ! -e build ]]; then
    pushd ${GTEST_DIR}
    echo "Building with >${build}< Configure with: >${cmakeType}<"
    mkdir build
    cd build
    cmake -DCMAKE_INSTALL_PREFIX=${THORSANVIL_ROOT}/3rd   ..  ${cmakeType}
    ${build}
    ${build} install
    popd
fi

if [[ ! -e 3rd/include/Mock.h ]]; then

    cat - <<MOCKH > ${THORSANVIL_ROOT}/3rd/include/Mock.h

#ifndef THORSANVIL_BUILDTOOLS_SYNTAX_HIGHLITING_MOCK_H
#define THORSANVIL_BUILDTOOLS_SYNTAX_HIGHLITING_MOCK_H

#define MOCK_FUNC(x) x

#endif

MOCKH

fi


