#!/bin/bash

#
# Change this as required to point at the root of ThorsAnvil code
FPN=$(pwd)/$0
ROOT=$(dirname $FPN)
THORSANVIL_ROOT=$(dirname ${ROOT})

pushd ${THORSANVIL_ROOT}
git submodule init
git submodule update
popd


install="sudo apt-get --yes"

host=`uname`
if [[ "${host}" == "Darwin" ]]; then 
	# This is a mac use brew
	install="brew"
fi

${install} install wget

pushd ${ROOT}
echo "Un-archiving google test"
GTEST_ARCHIEVE=`ls gtest-*.zip 2>/dev/null | tail -n 1`
if [[ ${GTEST_ARCHIEVE} == "" ]]; then
    echo "Retrieving: gtest-1.7.0"
    wget http://googletest.googlecode.com/files/gtest-1.7.0.zip
    GTEST_ARCHIEVE=`ls gtest-*.zip 2>/dev/null | tail -n 1`
fi
GTEST_ARCHIEVE_DIR=${GTEST_ARCHIEVE%.zip}

if [[ ! -d ${GTEST_ARCHIEVE_DIR} ]]; then
    unzip ${GTEST_ARCHIEVE}
fi
popd

echo "Building google test"
GTEST_DIR=${ROOT}/${GTEST_ARCHIEVE_DIR}
pushd ${GTEST_DIR}
g++ -I${GTEST_DIR}/include -I${GTEST_DIR} -c ${GTEST_DIR}/src/gtest-all.cc
g++ -I${GTEST_DIR}/include -I${GTEST_DIR} -c ${GTEST_DIR}/src/gtest_main.cc
ar -rv libgtest.a gtest-all.o gtest_main.o
popd

echo "Installing google test"
pushd ${THORSANVIL_ROOT}
mkdir -p bin include include3rd lib
rm -f lib/libgtest.*
cp ${GTEST_DIR}/libgtest.a lib/
rm -f include3rd/gtest
ln -s ${GTEST_DIR}/include/gtest include3rd/gtest
popd


