#!/bin/bash


echo "Configuring"
rm configure
autoreconf --install

cat - configure << SUBMODULE_UPDATE > config.tmp
#!/bin/sh

if git submodule status | grep build | grep --quiet '^-'; then
    git submodule update --init --recursive build
fi

SUBMODULE_UPDATE

mv config.tmp configure
chmod +x configure
echo "" > Makefile.extra.in

#fixConfigHIn
#   This section is also in the init file

    grep -A1 -B2 HEADER_ONLY config.h.in > config.HO

    grep -v HEADER_ONLY config.h.in | awk '/^#define  [A-Z_]*_CONFIG_H$/ {print $0;print "#ifndef  THORS_PACKAGE_INFO_CONFIG_H"; print "#define  THORS_PACKAGE_INFO_CONFIG_H";next;} /^#endif$/ {next;} {print $0}' > config.tmp
    echo "#endif" >> config.tmp
    echo "" >> config.tmp
    cat config.HO >> config.tmp
    echo "" >> config.tmp
    echo "#endif" >> config.tmp

    mv config.tmp config.h.in
    rm config.HO

#fixConfigHIn END

rm -f configure~
rm -f config.h.in~
rm -f confdefs.h

